name = "MakieApp"
uuid = "37d4a051-6180-4ae2-9c2f-4e37d2b7b260"
authors = ["Janis Erdmanis <janiserdmanis@protonmail.ch>"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
GLMakie = "0.13.6"
