[AppBundler]
publisher_name = "AppBundler"
app_summary = "This is a default app summary"
app_description = "A longer description of the app"
windowed = false
compress = true
overwrite_target = false
bundler = "juliaimg"
selfsign = false
skipsign = false

[AppBundler.msix]
publisher = "CN=AppBundler, C=XX, O=PeaceFounder"
path_length_threshold = 260
skip_long_paths = false
skip_symlinks = true
skip_unicode_paths = true
bootstrapper = false
bootstrapper_windowed = false

[AppBundler.dmg]
shallow_signing = true
hardened_runtime = true
sandboxed_runtime = false
compression = "lzma"
backend = "xorriso"
xorriso.hfsplus = false
hfsplus.slack = 0.02

[AppBundler.appimage]
compression = "zstd"

[AppBundler.juliaimg]
mainless = false
precompile = true
incremental = false
sysimg = []
selective_assets = false

[AppBundler.juliac]
trim = false