name: Tests

on:
  push:
    branches: [main, master, dmg, ci-refactor]
    tags: ['*']
  pull_request:

jobs:
  test:
    name: Julia - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            prefix: xvfb-run -s '-screen 0 1024x768x24'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Linux GUI dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y xvfb libgtk-4-dev
        
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'
      
      - name: Setup tmate session (for debugging)
        if: runner.os == 'Windows'
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true  # Only you can access
      
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          prefix: ${{ matrix.prefix }}
        env:
          DISPLAY: ":0"
      - uses: julia-actions/julia-processcoverage@v1
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info
